import {
  PrismaClient,
  Role,
  BuyerType,
  BuyerIntent,
  EmailStatus,
  OutreachStatus,
  ConsentStatus,
  ProductCategory,
  OpportunityStage,
  TradeTerm,
  QuotationStatus,
  CampaignStatus,
  ActivityType,
} from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting EXPORT AI database seed...");

  // ─── 1. Users (Consistent demo credentials) ──────────────────────────────
  const adminPasswordHash = await bcrypt.hash("Admin@123456", 12);
  const managerPasswordHash = await bcrypt.hash("Manager@123456", 12);
  const agentPasswordHash = await bcrypt.hash("Agent@123456", 12);

  const admin = await prisma.user.upsert({
    where: { email: "admin@exportai.com" },
    update: {
      password: adminPasswordHash,
      role: Role.ADMIN,
      isActive: true,
      isApproved: true,
    },
    create: {
      name: "Naina Admin",
      email: "admin@exportai.com",
      password: adminPasswordHash,
      role: Role.ADMIN,
      phone: "+91 98765 43210",
      isActive: true,
      isApproved: true,
    },
  });

  const manager = await prisma.user.upsert({
    where: { email: "manager@exportai.com" },
    update: {
      password: managerPasswordHash,
      role: Role.MANAGER,
      isActive: true,
      isApproved: true,
    },
    create: {
      name: "Devon Sales Manager",
      email: "manager@exportai.com",
      password: managerPasswordHash,
      role: Role.MANAGER,
      phone: "+91 98765 33211",
      isActive: true,
      isApproved: true,
    },
  });

  const agent = await prisma.user.upsert({
    where: { email: "agent@exportai.com" },
    update: {
      password: agentPasswordHash,
      role: Role.AGENT,
      isActive: true,
      isApproved: true,
    },
    create: {
      name: "Rajesh Export Specialist",
      email: "agent@exportai.com",
      password: agentPasswordHash,
      role: Role.AGENT,
      phone: "+91 98765 12345",
      isActive: true,
      isApproved: true,
    },
  });

  console.log("👤 Seeded users:", admin.email, manager.email, agent.email);

  // ─── 2. Products (Singing Bowls & Acoustic Instruments) ───────────────────
  const productsData = [
    {
      name: "Tibetan Master Hand-Hammered Singing Bowl (Grade AAA)",
      slug: "tibetan-hand-hammered-singing-bowl-grade-aaa",
      sku: "SB-THH-001",
      category: ProductCategory.TIBETAN_HAND_HAMMERED,
      description: "Authentic 7-metal alloy hand-beaten meditation bowl made by master artisans in the Himalayan valley. Rich overtones with long sustain for sound bath and chakra alignment.",
      shortDescription: "Master hand-hammered 7-metal meditation bowl with deep resonance.",
      material: "7-Metal Bronze Alloy (Copper, Tin, Zinc, Iron, Silver, Gold, Lead)",
      frequency: "432 Hz / F Note (Heart Chakra)",
      diameter: "10-12 inches (25-30 cm)",
      weight: "1.8 - 2.2 kg",
      priceMin: 65.00,
      priceMax: 95.00,
      currency: "USD",
      moq: 10,
      stockQuantity: 250,
      availableForExport: true,
      exportMarkets: ["USA", "UK", "Germany", "Canada", "Australia", "Japan"],
      featured: true,
      thumbnailUrl: "https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&w=800&q=80",
    },
    {
      name: "7-Chakra Healing Singing Bowl Set (Complete with Accessories)",
      slug: "7-chakra-healing-singing-bowl-set",
      sku: "SB-7CK-SET",
      category: ProductCategory.CHAKRA_SET_7,
      description: "Tuned set of 7 singing bowls representing each chakra (Root to Crown). Includes 7 brocade silk ring cushions, 2 suede-wrapped wooden mallets, and 1 felt gong striker.",
      shortDescription: "Complete 7-bowl harmonic chakra set tuned to C, D, E, F, G, A, B notes.",
      material: "High-grade Bell Metal Bronze",
      frequency: "432 Hz tuned harmonic scale",
      diameter: "5 to 11 inches (12 to 28 cm)",
      weight: "6.5 kg (Complete Set)",
      priceMin: 220.00,
      priceMax: 310.00,
      currency: "USD",
      moq: 5,
      stockQuantity: 120,
      availableForExport: true,
      exportMarkets: ["USA", "UK", "Germany", "Canada", "France", "Netherlands"],
      featured: true,
      thumbnailUrl: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80",
    },
    {
      name: "Full Moon Energized Singing Bowl",
      slug: "full-moon-energized-singing-bowl",
      sku: "SB-FM-003",
      category: ProductCategory.FULL_MOON_BOWL,
      description: "Handcrafted exclusively during full moon nights under moonlight chanting. Highly revered by sound therapists and holistic practitioners for high vibration frequency.",
      shortDescription: "Rare ceremonial full-moon crafted singing bowl with exceptional sustain.",
      material: "Pure Virgin 7-Metal Alloy",
      frequency: "528 Hz (Miracle Tone / DNA Repair)",
      diameter: "9-10 inches (22-25 cm)",
      weight: "1.4 - 1.7 kg",
      priceMin: 85.00,
      priceMax: 130.00,
      currency: "USD",
      moq: 10,
      stockQuantity: 80,
      availableForExport: true,
      exportMarkets: ["USA", "UK", "Germany", "Switzerland", "Japan"],
      featured: true,
      thumbnailUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    },
    {
      name: "Frosted Crystal Quartz Singing Bowl (432Hz Chakra Tuned)",
      slug: "frosted-crystal-quartz-singing-bowl-432hz",
      sku: "SB-CQB-004",
      category: ProductCategory.CRYSTAL_QUARTZ,
      description: "99.99% pure optical quartz crystal bowl with heavy frosting. Produces clear, potent acoustic energy fields for meditation rooms and yoga studios.",
      shortDescription: "99.99% pure quartz crystal singing bowl with heavy frosted finish.",
      material: "Optical Grade Pure Quartz Crystal",
      frequency: "432 Hz / D Note (Sacral Chakra)",
      diameter: "8 inches (20 cm)",
      weight: "1.2 kg",
      priceMin: 45.00,
      priceMax: 70.00,
      currency: "USD",
      moq: 15,
      stockQuantity: 300,
      availableForExport: true,
      exportMarkets: ["USA", "Canada", "Australia", "UK", "Germany"],
      featured: false,
      thumbnailUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80",
    },
    {
      name: "Hand-Hammered Himalayan Temple Gong with Stand",
      slug: "hand-hammered-himalayan-temple-gong",
      sku: "TG-HIM-005",
      category: ProductCategory.TEMPLE_GONG,
      description: "Traditional heavy bell bronze gong with turned rim and engraved sacred geometry mandala. Deep, thunderous bass wash with immense vibrational depth.",
      shortDescription: "Traditional hand-hammered temple wind gong for sound healing sanctuaries.",
      material: "B20 Bronze Alloy",
      frequency: "Sub-bass multi-tonal wash",
      diameter: "22-24 inches (55-60 cm)",
      weight: "4.8 kg",
      priceMin: 180.00,
      priceMax: 260.00,
      currency: "USD",
      moq: 3,
      stockQuantity: 40,
      availableForExport: true,
      exportMarkets: ["USA", "Germany", "UK", "Japan", "Norway"],
      featured: false,
      thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    },
  ];

  for (const item of productsData) {
    await prisma.product.upsert({
      where: { sku: item.sku },
      update: {},
      create: item,
    });
  }

  console.log(`📦 Seeded ${productsData.length} export products.`);

  // ─── 3. Buyer Leads (~22 realistic international wholesale prospects) ────
  // Fictional wholesale names across 9 international export corridors
  // Varied scores create realistic quality bands: 90-100, 80-89, 70-79, <70
  const buyerLeadsData = [
    // Germany (3)
    {
      companyName: "Klangtherapie Zentrum München GmbH",
      contactPerson: "Dr. Markus Weber",
      email: "einkauf@klangtherapie-muenchen.de",
      normalizedEmail: "einkauf@klangtherapie-muenchen.de",
      phone: "+49 89 2345 6789",
      website: "https://klangtherapie-muenchen.de",
      country: "Germany",
      city: "Munich",
      source: "German Sound Therapy Academy Registry",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_de_klang_001",
      buyerType: BuyerType.STUDIO,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Professional Sound Therapy Academy & Clinic",
      productInterest: "432Hz Tuned Chakra Sets & Temple Gongs",
      leadScore: 92,
      aiConfidence: 0.94,
      aiReasoning: "German certified sound healing training institute. Regularly purchases 20-30 sets per quarter for graduating practitioners.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 3),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "RFC 5322 Syntax Valid, MX Record Active",
      outreachStatus: OutreachStatus.REPLIED,
      lastContactedAt: new Date(Date.now() - 86400000 * 2),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Bavaria Holistic Wellness Grosshandel",
      contactPerson: "Greta Schmidt",
      email: "order@bavaria-wellness-grosshandel.de",
      normalizedEmail: "order@bavaria-wellness-grosshandel.de",
      phone: "+49 911 876 5432",
      website: "https://bavaria-wellness-grosshandel.de",
      country: "Germany",
      city: "Nuremberg",
      source: "B2B European Wholesaler Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_de_bavaria_002",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Holistic Health Wholesale Distribution",
      productInterest: "Tibetan Master Hand-Hammered Singing Bowls",
      leadScore: 88,
      aiConfidence: 0.91,
      aiReasoning: "Supplies 60+ wellness hotels and sauna complexes in Southern Germany and Austria.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 5),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "MX Record Verified",
      outreachStatus: OutreachStatus.SENT,
      lastContactedAt: new Date(Date.now() - 86400000 * 4),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Aura Klangwelt Berlin e.K.",
      contactPerson: "Stefan Brandt",
      email: "info@aura-klangwelt-berlin.de",
      normalizedEmail: "info@aura-klangwelt-berlin.de",
      phone: "+49 30 5544 3322",
      website: "https://aura-klangwelt-berlin.de",
      country: "Germany",
      city: "Berlin",
      source: "Web Search",
      sourcePlatform: "WEBSITE",
      sourceExternalId: "web_de_aura_003",
      buyerType: BuyerType.RETAILER,
      buyerIntent: BuyerIntent.MEDIUM,
      industry: "Meditation Lifestyle Boutiques",
      productInterest: "Frosted Crystal Quartz Singing Bowls",
      leadScore: 78,
      aiConfidence: 0.82,
      aiReasoning: "Operates 2 experiential boutique shops in Berlin Mitte; moderate purchasing budget.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 7),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "Syntax Valid",
      outreachStatus: OutreachStatus.NOT_CONTACTED,
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.UNKNOWN,
      assignedToId: agent.id,
      createdById: admin.id,
    },

    // USA (4)
    {
      companyName: "Zenith Sound & Wellness Imports LLC",
      contactPerson: "Jonathan Miller",
      email: "jmiller@zenithsoundwellness.com",
      normalizedEmail: "jmiller@zenithsoundwellness.com",
      phone: "+1 (415) 890-4321",
      website: "https://zenithsoundwellness.com",
      country: "USA",
      city: "San Francisco, CA",
      source: "Google B2B Search",
      sourcePlatform: "GOOGLE",
      sourceExternalId: "goog_us_zenith_004",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Sound Healing & Holistic Distribution",
      productInterest: "7-Chakra Sets & Tibetan Master Bowls",
      leadScore: 94,
      aiConfidence: 0.96,
      aiReasoning: "Large wholesale distributor supplying 140+ yoga studios and meditation centers across California and Oregon.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 2),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "RFC 5322 Syntax Valid, MX Active (Google Workspace)",
      outreachStatus: OutreachStatus.REPLIED,
      lastContactedAt: new Date(Date.now() - 86400000 * 1),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Pacific Meditation & Acoustic Arts Inc",
      contactPerson: "Sarah Chen",
      email: "schen@pacificacousticarts.com",
      normalizedEmail: "schen@pacificacousticarts.com",
      phone: "+1 (206) 555-7890",
      website: "https://pacificacousticarts.com",
      country: "USA",
      city: "Seattle, WA",
      source: "Trade Show Lead Sheet",
      sourcePlatform: "CSV",
      sourceExternalId: "csv_us_pacific_005",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Sound Therapy Equipment Supply",
      productInterest: "Hand-Hammered Himalayan Temple Gongs & Bowls",
      leadScore: 89,
      aiConfidence: 0.92,
      aiReasoning: "Major supplier to sound bath practitioners in the Pacific Northwest.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 4),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "MX Verified",
      outreachStatus: OutreachStatus.SENT,
      lastContactedAt: new Date(Date.now() - 86400000 * 3),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Sedona Sound Temple Retailers",
      contactPerson: "Michael Vance",
      email: "michael@sedonasoundtemple.com",
      normalizedEmail: "michael@sedonasoundtemple.com",
      phone: "+1 (928) 282-1144",
      website: "https://sedonasoundtemple.com",
      country: "USA",
      city: "Sedona, AZ",
      source: "Holistic Retail Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_us_sedona_006",
      buyerType: BuyerType.RETAILER,
      buyerIntent: BuyerIntent.MEDIUM,
      industry: "Vortex Meditation & Healing Center",
      productInterest: "432Hz Chakra Singing Bowl Sets",
      leadScore: 84,
      aiConfidence: 0.88,
      aiReasoning: "High foot-traffic sound temple in Sedona with high retail margins.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 6),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "MX Verified",
      outreachStatus: OutreachStatus.SENT,
      lastContactedAt: new Date(Date.now() - 86400000 * 5),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.OPT_IN,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Manhattan Mindfulness Collective",
      contactPerson: "Chloe Adams",
      email: "cadams@manhattanmindfulness.org",
      normalizedEmail: "cadams@manhattanmindfulness.org",
      phone: "+1 (212) 555-0199",
      website: "https://manhattanmindfulness.org",
      country: "USA",
      city: "New York, NY",
      source: "Web Search",
      sourcePlatform: "WEBSITE",
      sourceExternalId: "web_us_manhattan_007",
      buyerType: BuyerType.STUDIO,
      buyerIntent: BuyerIntent.LOW,
      industry: "Executive Meditation Studio",
      productInterest: "Full Moon Energized Bowls",
      leadScore: 72,
      aiConfidence: 0.76,
      aiReasoning: "High brand prestige but primarily studio user rather than bulk reseller.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 8),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "Syntax OK",
      outreachStatus: OutreachStatus.NOT_CONTACTED,
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.UNKNOWN,
      assignedToId: agent.id,
      createdById: admin.id,
    },

    // UK (3)
    {
      companyName: "Bodhi Tree Holistic Living Ltd",
      contactPerson: "Eleanor Vance",
      email: "eleanor@bodhitreeholistic.co.uk",
      normalizedEmail: "eleanor@bodhitreeholistic.co.uk",
      phone: "+44 20 7946 0912",
      website: "https://bodhitreeholistic.co.uk",
      country: "UK",
      city: "London",
      source: "Holistic Retail Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_uk_bodhi_008",
      buyerType: BuyerType.RETAILER,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Spiritual Lifestyle & Sound Bath Studio Chain",
      productInterest: "Tibetan Hand-Hammered Bowls & Full Moon Bowls",
      leadScore: 91,
      aiConfidence: 0.93,
      aiReasoning: "Owns 4 premium lifestyle wellness stores in London & Edinburgh with weekly sound bath workshops.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 3),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "RFC 5322 Syntax Valid, MX Active",
      outreachStatus: OutreachStatus.REPLIED,
      lastContactedAt: new Date(Date.now() - 86400000 * 2),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Cotswolds Sound Sanctuary Wholesale",
      contactPerson: "Arthur Pendelton",
      email: "arthur@cotswoldssoundsanctuary.co.uk",
      normalizedEmail: "arthur@cotswoldssoundsanctuary.co.uk",
      phone: "+44 1451 830123",
      website: "https://cotswoldssoundsanctuary.co.uk",
      country: "UK",
      city: "Bristol",
      source: "Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_uk_cotswolds_009",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Sound Healing Distribution & Training",
      productInterest: "7-Chakra Harmonic Sets",
      leadScore: 85,
      aiConfidence: 0.89,
      aiReasoning: "Provides instruments to 35+ accredited sound therapists across the South of England.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 6),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "MX Verified",
      outreachStatus: OutreachStatus.SENT,
      lastContactedAt: new Date(Date.now() - 86400000 * 4),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Avalon Healing Instruments UK",
      contactPerson: "Fiona MacLeod",
      email: "fiona@avalonhealinginstruments.co.uk",
      normalizedEmail: "fiona@avalonhealinginstruments.co.uk",
      phone: "+44 1458 834567",
      website: "https://avalonhealinginstruments.co.uk",
      country: "UK",
      city: "Glastonbury",
      source: "Web Inquiry",
      sourcePlatform: "WEBSITE",
      sourceExternalId: "web_uk_avalon_010",
      buyerType: BuyerType.RETAILER,
      buyerIntent: BuyerIntent.LOW,
      industry: "Metaphysical & Sound Arts Gift Shop",
      productInterest: "Himalayan Bronze Singing Bowls",
      leadScore: 68,
      aiConfidence: 0.72,
      aiReasoning: "Seasonal tourist footfall; lower overall order volumes.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 10),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "Syntax OK",
      outreachStatus: OutreachStatus.NOT_CONTACTED,
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.UNKNOWN,
      assignedToId: agent.id,
      createdById: admin.id,
    },

    // Canada (2)
    {
      companyName: "Prana Meditation Supplies Canada",
      contactPerson: "David Tremblay",
      email: "david@pranameditation.ca",
      normalizedEmail: "david@pranameditation.ca",
      phone: "+1 (514) 789-0123",
      website: "https://pranameditation.ca",
      country: "Canada",
      city: "Montreal, QC",
      source: "CSV Import Batch #1",
      sourcePlatform: "CSV",
      sourceExternalId: "csv_ca_prana_011",
      buyerType: BuyerType.BUSINESS,
      buyerIntent: BuyerIntent.HIGH,
      industry: "E-Commerce Yoga & Meditation Equipment",
      productInterest: "Frosted Crystal Quartz Bowls & Tibetan Bowls",
      leadScore: 82,
      aiConfidence: 0.88,
      aiReasoning: "Canadian e-commerce brand with strong Amazon & Shopify presence selling meditation accessories.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 4),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "RFC 5322 Syntax Valid, MX Active",
      outreachStatus: OutreachStatus.SENT,
      lastContactedAt: new Date(Date.now() - 86400000 * 3),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.UNKNOWN,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Vancouver Sound Therapy Exchange",
      contactPerson: "Liam O'Connor",
      email: "liam@vancouversoundexchange.ca",
      normalizedEmail: "liam@vancouversoundexchange.ca",
      phone: "+1 (604) 688-9922",
      website: "https://vancouversoundexchange.ca",
      country: "Canada",
      city: "Vancouver, BC",
      source: "Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_ca_vancouver_012",
      buyerType: BuyerType.STUDIO,
      buyerIntent: BuyerIntent.MEDIUM,
      industry: "Acoustic Healing & Sound Academy",
      productInterest: "7-Chakra Tuned Sets & Mallets",
      leadScore: 76,
      aiConfidence: 0.80,
      aiReasoning: "Established yoga studio network in British Columbia.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 9),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "MX Verified",
      outreachStatus: OutreachStatus.NOT_CONTACTED,
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.OPT_IN,
      assignedToId: agent.id,
      createdById: admin.id,
    },

    // Australia (3)
    {
      companyName: "Byron Bay Holistic Spa Distribution",
      contactPerson: "Kylie Hemsworth",
      email: "kylie@byronholisticdistribution.com.au",
      normalizedEmail: "kylie@byronholisticdistribution.com.au",
      phone: "+61 2 6685 4321",
      website: "https://byronholisticdistribution.com.au",
      country: "Australia",
      city: "Byron Bay, NSW",
      source: "Google B2B Search",
      sourcePlatform: "GOOGLE",
      sourceExternalId: "goog_au_byron_013",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Luxury Eco-Resort & Spa Supply Wholesaler",
      productInterest: "Full Moon Bowls & 7-Chakra Sets",
      leadScore: 93,
      aiConfidence: 0.95,
      aiReasoning: "Premier wellness equipment supplier for 80+ luxury day spas and retreats across NSW and Queensland.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 2),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "MX Active (Microsoft 365)",
      outreachStatus: OutreachStatus.REPLIED,
      lastContactedAt: new Date(Date.now() - 86400000 * 1),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Sydney Acoustic Wellness Chain",
      contactPerson: "Brett Taylor",
      email: "btaylor@sydneyacousticwellness.com.au",
      normalizedEmail: "btaylor@sydneyacousticwellness.com.au",
      phone: "+61 2 9234 5678",
      website: "https://sydneyacousticwellness.com.au",
      country: "Australia",
      city: "Sydney, NSW",
      source: "Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_au_sydney_014",
      buyerType: BuyerType.RETAILER,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Holistic Health Lifestyle Stores",
      productInterest: "Hand-Hammered Singing Bowls & Gongs",
      leadScore: 81,
      aiConfidence: 0.86,
      aiReasoning: "5 flagship retail storefronts in Sydney metro area.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 5),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "Syntax Valid",
      outreachStatus: OutreachStatus.SENT,
      lastContactedAt: new Date(Date.now() - 86400000 * 3),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Melbourne Sound Healing Guild",
      contactPerson: "Gemma Lawson",
      email: "gemma@melbournesoundhealing.com.au",
      normalizedEmail: "gemma@melbournesoundhealing.com.au",
      phone: "+61 3 9419 8765",
      website: "https://melbournesoundhealing.com.au",
      country: "Australia",
      city: "Melbourne, VIC",
      source: "Web Search",
      sourcePlatform: "WEBSITE",
      sourceExternalId: "web_au_melbourne_015",
      buyerType: BuyerType.STUDIO,
      buyerIntent: BuyerIntent.LOW,
      industry: "Acoustic Meditation Co-operative",
      productInterest: "Tibetan Master Hand-Hammered Bowls",
      leadScore: 65,
      aiConfidence: 0.70,
      aiReasoning: "Cooperative guild with periodic group purchases; requires low MOQ.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 11),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "Syntax OK",
      outreachStatus: OutreachStatus.NOT_CONTACTED,
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.UNKNOWN,
      assignedToId: agent.id,
      createdById: admin.id,
    },

    // France (2)
    {
      companyName: "Maison du Son & Méditation Paris",
      contactPerson: "Claire Dubois",
      email: "cdubois@maisonduson-paris.fr",
      normalizedEmail: "cdubois@maisonduson-paris.fr",
      phone: "+33 1 42 68 55 00",
      website: "https://maisonduson-paris.fr",
      country: "France",
      city: "Paris",
      source: "French Wellness Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_fr_maison_016",
      buyerType: BuyerType.RETAILER,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Artisanal Himalayan Instrument Concept Store",
      productInterest: "Tibetan Master Singing Bowls & Temple Gongs",
      leadScore: 87,
      aiConfidence: 0.90,
      aiReasoning: "Prestigious Parisian wellness boutique in Saint-Germain-des-Prés.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 4),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "RFC 5322 Syntax Valid, MX Active",
      outreachStatus: OutreachStatus.REPLIED,
      lastContactedAt: new Date(Date.now() - 86400000 * 2),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Provence Bien-Être Distribution SARL",
      contactPerson: "Antoine Mercier",
      email: "contact@provence-bienetre.fr",
      normalizedEmail: "contact@provence-bienetre.fr",
      phone: "+33 4 91 22 33 44",
      website: "https://provence-bienetre.fr",
      country: "France",
      city: "Marseille",
      source: "Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_fr_provence_017",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.MEDIUM,
      industry: "Spa & Thalassotherapy Equipment Supply",
      productInterest: "Crystal Quartz Singing Bowls",
      leadScore: 79,
      aiConfidence: 0.83,
      aiReasoning: "Supplies Mediterranean thalassotherapy wellness centers.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 7),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "MX Verified",
      outreachStatus: OutreachStatus.SENT,
      lastContactedAt: new Date(Date.now() - 86400000 * 5),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.UNKNOWN,
      assignedToId: agent.id,
      createdById: admin.id,
    },

    // Netherlands (2)
    {
      companyName: "Amsterdam Sound Bath Wholesale B.V.",
      contactPerson: "Diederik van der Berg",
      email: "diederik@amsterdamsoundbath.nl",
      normalizedEmail: "diederik@amsterdamsoundbath.nl",
      phone: "+31 20 654 3210",
      website: "https://amsterdamsoundbath.nl",
      country: "Netherlands",
      city: "Amsterdam",
      source: "Benelux Holistic Registry",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_nl_amsterdam_018",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Benelux Sound Healing Wholesale",
      productInterest: "7-Chakra Harmonic Sets & Master Bowls",
      leadScore: 86,
      aiConfidence: 0.89,
      aiReasoning: "Servicing over 90 holistic practitioners and yoga studios across the Netherlands, Belgium, and Luxembourg.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 3),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "RFC 5322 Syntax Valid, MX Active",
      outreachStatus: OutreachStatus.REPLIED,
      lastContactedAt: new Date(Date.now() - 86400000 * 2),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Nordic Holistic Imports Rotterdam",
      contactPerson: "Sanne Jansen",
      email: "sjansen@nordicholistic.nl",
      normalizedEmail: "sjansen@nordicholistic.nl",
      phone: "+31 10 765 4321",
      website: "https://nordicholistic.nl",
      country: "Netherlands",
      city: "Rotterdam",
      source: "CSV Import Batch #2",
      sourcePlatform: "CSV",
      sourceExternalId: "csv_nl_nordic_019",
      buyerType: BuyerType.BUSINESS,
      buyerIntent: BuyerIntent.MEDIUM,
      industry: "Eco-Retail & Meditation Import Trade",
      productInterest: "Full Moon Bowls & Accessories",
      leadScore: 74,
      aiConfidence: 0.78,
      aiReasoning: "Rotterdam port-adjacent distributor seeking direct manufacturer container pricing.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 8),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "Syntax Valid",
      outreachStatus: OutreachStatus.NOT_CONTACTED,
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.UNKNOWN,
      assignedToId: agent.id,
      createdById: admin.id,
    },

    // UAE (2)
    {
      companyName: "Dubai Luxury Spa & Wellness Imports LLC",
      contactPerson: "Tariq Al-Mansoor",
      email: "talmansoor@dubailuxuryspa.ae",
      normalizedEmail: "talmansoor@dubailuxuryspa.ae",
      phone: "+971 4 345 6789",
      website: "https://dubailuxuryspa.ae",
      country: "UAE",
      city: "Dubai",
      source: "Gulf B2B Trade Directory",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_ae_dubai_020",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Ultra-Luxury 5-Star Hotel Spas & Sound Lounges",
      productInterest: "Temple Gongs & Master Hand-Hammered Singing Bowls",
      leadScore: 90,
      aiConfidence: 0.94,
      aiReasoning: "Supplies sound sanctuary instruments to luxury hotel chains in Dubai, Abu Dhabi, and Doha.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 2),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "RFC 5322 Valid, MX Verified",
      outreachStatus: OutreachStatus.SENT,
      lastContactedAt: new Date(Date.now() - 86400000 * 1),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.OPT_IN,
      assignedToId: agent.id,
      createdById: admin.id,
    },
    {
      companyName: "Abu Dhabi Holistic Living Trade",
      contactPerson: "Fatima Al-Nuaimi",
      email: "fatima@abudhabiholistic.ae",
      normalizedEmail: "fatima@abudhabiholistic.ae",
      phone: "+971 2 567 8901",
      website: "https://abudhabiholistic.ae",
      country: "UAE",
      city: "Abu Dhabi",
      source: "Trade Inquiries",
      sourcePlatform: "WEBSITE",
      sourceExternalId: "web_ae_abudhabi_021",
      buyerType: BuyerType.RETAILER,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Holistic Wellness Boutiques",
      productInterest: "Chakra 7-Set Bell Bronze Bowls",
      leadScore: 83,
      aiConfidence: 0.87,
      aiReasoning: "High disposable income clientele; interested in gold/silver certified alloy bowls.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 5),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "MX Active",
      outreachStatus: OutreachStatus.NOT_CONTACTED,
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.UNKNOWN,
      assignedToId: agent.id,
      createdById: admin.id,
    },

    // Japan (1)
    {
      companyName: "Kyoto Sound Healing Artisans Co.",
      contactPerson: "Kenji Takahashi",
      email: "takahashi@kyotosoundhealing.jp",
      normalizedEmail: "takahashi@kyotosoundhealing.jp",
      phone: "+81 75 432 1098",
      website: "https://kyotosoundhealing.jp",
      country: "Japan",
      city: "Kyoto",
      source: "International Artisan Association Registry",
      sourcePlatform: "DIRECTORY",
      sourceExternalId: "dir_jp_kyoto_022",
      buyerType: BuyerType.DISTRIBUTOR,
      buyerIntent: BuyerIntent.HIGH,
      industry: "Zen Temple & Traditional Meditation Acoustic Supply",
      productInterest: "Authentic Master Hand-Hammered 7-Metal Singing Bowls",
      leadScore: 95,
      aiConfidence: 0.97,
      aiReasoning: "High-volume wholesale buyer supplying Zen Buddhist temples and sound therapy practitioners throughout Kansai and Kanto regions.",
      aiModel: "gemini-1.5-flash",
      aiProcessedAt: new Date(Date.now() - 86400000 * 1),
      emailStatus: EmailStatus.VALID,
      verificationStatus: "RFC 5322 Syntax Valid, MX Active",
      outreachStatus: OutreachStatus.REPLIED,
      lastContactedAt: new Date(Date.now() - 86400000 * 1),
      unsubscribeStatus: false,
      consentStatus: ConsentStatus.SUBSCRIBED,
      assignedToId: agent.id,
      createdById: admin.id,
    },
  ];

  for (const lead of buyerLeadsData) {
    await prisma.buyerLead.upsert({
      where: { normalizedEmail: lead.normalizedEmail },
      update: {
        companyName: lead.companyName,
        contactPerson: lead.contactPerson,
        country: lead.country,
        city: lead.city,
        buyerType: lead.buyerType,
        buyerIntent: lead.buyerIntent,
        industry: lead.industry,
        productInterest: lead.productInterest,
        leadScore: lead.leadScore,
        emailStatus: lead.emailStatus,
        outreachStatus: lead.outreachStatus,
        assignedToId: lead.assignedToId,
      },
      create: lead,
    });
  }

  console.log(`🎯 Seeded ${buyerLeadsData.length} qualified international buyer leads.`);

  // ─── 4. Reusable Email Templates ─────────────────────────────────────────
  const templatesData = [
    {
      name: "Wholesale Singing Bowls — Manufacturer Direct Introduction",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls for {{companyName}}",
      body: `Hello {{firstName}},\n\nI noticed that {{companyName}} is recognized for delivering premium sound therapy and meditation experiences in {{country}}.\n\nWe are direct artisanal manufacturers and exporters of authentic hand-hammered 7-metal Tibetan Singing Bowls, tuned 432Hz Chakra sets, and Himalayan Temple Gongs.\n\n{{aiPersonalizedIntro}}\n\nWhy international distributors partner with us:\n• Direct Himalayan artisan workshop FOB/CIF pricing (up to 40% margin improvement over trading intermediaries)\n• Guaranteed acoustic frequency tuning (432Hz / 528Hz verified)\n• Complete export documentation, lab metal purity certificates, and custom laser branding\n• Low MOQ with rapid sample courier dispatch\n\nWould you be open to reviewing our wholesale export catalog and FOB price sheet for {{country}}?\n\nWarm regards,\n\nExport Sales Director\nExport AI — Himalayan Singing Bowls\n{{website}}`,
      variables: ["firstName", "companyName", "country", "productName", "website", "aiPersonalizedIntro"],
      category: "Wholesale Outreach",
      isDefault: true,
      createdById: admin.id,
    },
    {
      name: "7-Chakra Harmonic Set — Sound Therapy Studio Special",
      subject: "Wholesale 7-Chakra Tuned Bowl Sets for {{companyName}} Sound Practitioners",
      body: `Dear {{firstName}},\n\nFollowing {{companyName}}'s ongoing work in sound meditation and holistic healing in {{country}}, I wanted to share our newly released 432Hz harmonic 7-Chakra singing bowl series.\n\n{{aiPersonalizedIntro}}\n\nEach set is handcrafted from virgin bell metal bronze, acoustically tested for pitch accuracy across C-D-E-F-G-A-B chakra frequencies, and comes complete with brocade silk cushions and dual suede mallets.\n\nWe currently offer trial sample shipments with DHL Express door-to-door delivery.\n\nMay I send you our technical specification sheet and wholesale quotation?\n\nBest regards,\n\nExport Team\nHimalayan Sound Instruments`,
      variables: ["firstName", "companyName", "country", "productName", "website", "aiPersonalizedIntro"],
      category: "Studio & Academy Outreach",
      isDefault: false,
      createdById: admin.id,
    },
  ];

  for (const tpl of templatesData) {
    const existing = await prisma.emailTemplate.findFirst({ where: { name: tpl.name } });
    if (!existing) {
      await prisma.emailTemplate.create({ data: tpl });
    }
  }

  // ─── 5. Campaigns (3 diverse statuses: RUNNING, COMPLETED, DRAFT) ─────────
  const productChakra = await prisma.product.findUnique({ where: { sku: "SB-7CK-SET" } });
  const productTibetan = await prisma.product.findUnique({ where: { sku: "SB-THH-001" } });
  const productMoon = await prisma.product.findUnique({ where: { sku: "SB-FM-003" } });
  const defaultTemplate = await prisma.emailTemplate.findFirst({ where: { isDefault: true } });

  const campaignsData = [
    {
      id: "seed-camp-001",
      name: "Q3 DACH German Wellness Corridor Outreach",
      description: "Direct outreach sequence targeting sound meditation academies and holistic spas in Germany and Austria.",
      subject: "Direct Manufacturer Supply: Certified 432Hz Chakra Singing Bowls",
      templateId: defaultTemplate?.id || null,
      productId: productChakra?.id || null,
      status: CampaignStatus.RUNNING,
      totalRecipients: 8,
      sentCount: 6,
      failedCount: 0,
      repliedCount: 2,
      dailyLimit: 100,
      startedAt: new Date(Date.now() - 86400000 * 5),
      createdById: admin.id,
    },
    {
      id: "seed-camp-002",
      name: "US West Coast Sound Studio Expansion",
      description: "California and Oregon yoga studios wholesale singing bowl sets promotion.",
      subject: "Wholesale Hand-Hammered Himalayan Singing Bowls for US Sound Studios",
      templateId: defaultTemplate?.id || null,
      productId: productTibetan?.id || null,
      status: CampaignStatus.COMPLETED,
      totalRecipients: 12,
      sentCount: 12,
      failedCount: 0,
      repliedCount: 3,
      dailyLimit: 150,
      startedAt: new Date(Date.now() - 86400000 * 14),
      completedAt: new Date(Date.now() - 86400000 * 2),
      createdById: admin.id,
    },
    {
      id: "seed-camp-003",
      name: "UK Holistic Retailers Autumn Preview",
      description: "Full Moon ceremonial singing bowls introduction for UK holistic wellness boutiques.",
      subject: "Exclusive Preview: Full Moon Handcrafted Ceremonial Singing Bowls",
      templateId: defaultTemplate?.id || null,
      productId: productMoon?.id || null,
      status: CampaignStatus.DRAFT,
      totalRecipients: 5,
      sentCount: 0,
      failedCount: 0,
      repliedCount: 0,
      dailyLimit: 100,
      createdById: manager.id,
    },
  ];

  for (const camp of campaignsData) {
    await prisma.campaign.upsert({
      where: { id: camp.id },
      update: {
        status: camp.status,
        sentCount: camp.sentCount,
        repliedCount: camp.repliedCount,
        totalRecipients: camp.totalRecipients,
      },
      create: camp,
    });
  }

  console.log("📢 Seeded 3 campaigns (RUNNING, COMPLETED, DRAFT).");

  // ─── 6. Sales Opportunities (10 deals across all 8 pipeline stages) ──────
  const leadKlang = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "einkauf@klangtherapie-muenchen.de" } });
  const leadZenith = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "jmiller@zenithsoundwellness.com" } });
  const leadBodhi = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "eleanor@bodhitreeholistic.co.uk" } });
  const leadByron = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "kylie@byronholisticdistribution.com.au" } });
  const leadMaison = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "cdubois@maisonduson-paris.fr" } });
  const leadAmsterdam = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "diederik@amsterdamsoundbath.nl" } });
  const leadDubai = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "talmansoor@dubailuxuryspa.ae" } });
  const leadKyoto = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "takahashi@kyotosoundhealing.jp" } });
  const leadPacific = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "schen@pacificacousticarts.com" } });
  const leadAvalon = await prisma.buyerLead.findUnique({ where: { normalizedEmail: "fiona@avalonhealinginstruments.co.uk" } });

  const opportunitiesData = [
    {
      id: "seed-opp-001",
      title: "Dubai Luxury Spa — Initial Temple Gong & Master Bowls Evaluation",
      stage: OpportunityStage.PROSPECTING,
      inquiryValue: 18500.00,
      currency: "USD",
      quantity: 45,
      terms: TradeTerm.FOB,
      expectedCloseDate: new Date(Date.now() + 86400000 * 45),
      leadId: leadDubai!.id,
      productId: productTibetan?.id || null,
      assignedToId: agent.id,
      notes: "Prospective hotel spa chain in Palm Jumeirah considering sound bath installation.",
    },
    {
      id: "seed-opp-002",
      title: "Zenith Sound — West Coast Distribution 100x Chakra Sets",
      stage: OpportunityStage.QUALIFIED,
      inquiryValue: 32000.00,
      currency: "USD",
      quantity: 100,
      terms: TradeTerm.CIF,
      expectedCloseDate: new Date(Date.now() + 86400000 * 30),
      leadId: leadZenith!.id,
      productId: productChakra?.id || null,
      assignedToId: agent.id,
      notes: "Verified buyer requesting bulk CIF Port of Oakland quotation for Q4 inventory buildup.",
    },
    {
      id: "seed-opp-003",
      title: "Bodhi Tree Holistic — 4-Store London Retail Order",
      stage: OpportunityStage.CONTACTED,
      inquiryValue: 9400.00,
      currency: "USD",
      quantity: 35,
      terms: TradeTerm.FOB,
      expectedCloseDate: new Date(Date.now() + 86400000 * 25),
      leadId: leadBodhi!.id,
      productId: productMoon?.id || null,
      assignedToId: agent.id,
      notes: "Followed up after initial email reply; buyer requested full product spec catalog.",
    },
    {
      id: "seed-opp-004",
      title: "Byron Bay Spa — Acoustic Sound Immersion Package",
      stage: OpportunityStage.INTERESTED,
      inquiryValue: 15600.00,
      currency: "USD",
      quantity: 50,
      terms: TradeTerm.CIF,
      expectedCloseDate: new Date(Date.now() + 86400000 * 20),
      leadId: leadByron!.id,
      productId: productChakra?.id || null,
      assignedToId: agent.id,
      notes: "High interest in 432Hz harmonic 7-chakra tuned sets with custom logo laser engraving.",
    },
    {
      id: "seed-opp-005",
      title: "Pacific Acoustic — Annual Wholesale Contract Negotiation",
      stage: OpportunityStage.NEGOTIATION,
      inquiryValue: 24000.00,
      currency: "USD",
      quantity: 80,
      terms: TradeTerm.CIF,
      expectedCloseDate: new Date(Date.now() + 86400000 * 10),
      leadId: leadPacific!.id,
      productId: productTibetan?.id || null,
      assignedToId: agent.id,
      notes: "Finalizing payment terms: 30% advance, 70% against Bill of Lading scan.",
    },
    {
      id: "seed-opp-006",
      title: "Klangtherapie München — Q3 20x 7-Chakra Sets Proforma Order",
      stage: OpportunityStage.QUOTATION,
      inquiryValue: 4800.00,
      currency: "USD",
      quantity: 20,
      terms: TradeTerm.CIF,
      expectedCloseDate: new Date(Date.now() + 86400000 * 14),
      leadId: leadKlang!.id,
      productId: productChakra?.id || null,
      assignedToId: agent.id,
      notes: "Proforma quotation EXP-2026-000001 dispatched with CIF Munich terms.",
    },
    {
      id: "seed-opp-007",
      title: "Maison du Son Paris — Boutique Display Proforma Order",
      stage: OpportunityStage.QUOTATION,
      inquiryValue: 6200.00,
      currency: "USD",
      quantity: 25,
      terms: TradeTerm.EXW,
      expectedCloseDate: new Date(Date.now() + 86400000 * 18),
      leadId: leadMaison!.id,
      productId: productTibetan?.id || null,
      assignedToId: agent.id,
      notes: "Proforma quotation EXP-2026-000003 sent with EXW Kathmandu workshop terms.",
    },
    {
      id: "seed-opp-008",
      title: "Amsterdam Sound Bath — Spring Wholesale Consignment",
      stage: OpportunityStage.CLOSED_WON,
      inquiryValue: 12500.00,
      currency: "USD",
      quantity: 40,
      terms: TradeTerm.FOB,
      expectedCloseDate: new Date(Date.now() - 86400000 * 5),
      closedAt: new Date(Date.now() - 86400000 * 5),
      leadId: leadAmsterdam!.id,
      productId: productChakra?.id || null,
      assignedToId: agent.id,
      notes: "Order confirmed and deposit received. Quotation EXP-2026-000002 accepted.",
    },
    {
      id: "seed-opp-009",
      title: "Kyoto Sound Healing — Master Artisan Temple Collection",
      stage: OpportunityStage.CLOSED_WON,
      inquiryValue: 28000.00,
      currency: "USD",
      quantity: 90,
      terms: TradeTerm.CIF,
      expectedCloseDate: new Date(Date.now() - 86400000 * 3),
      closedAt: new Date(Date.now() - 86400000 * 3),
      leadId: leadKyoto!.id,
      productId: productTibetan?.id || null,
      assignedToId: agent.id,
      notes: "Quotation EXP-2026-000004 approved. Letter of Credit opened.",
    },
    {
      id: "seed-opp-010",
      title: "Avalon Healing Instruments — Sample Trial Order",
      stage: OpportunityStage.CLOSED_LOST,
      inquiryValue: 3200.00,
      currency: "USD",
      quantity: 10,
      terms: TradeTerm.EXW,
      expectedCloseDate: new Date(Date.now() - 86400000 * 8),
      closedAt: new Date(Date.now() - 86400000 * 8),
      lostReason: "Buyer selected a local UK reseller due to immediate 48-hour delivery requirement.",
      leadId: leadAvalon!.id,
      productId: productMoon?.id || null,
      assignedToId: agent.id,
      notes: "Lead lost to domestic stockist; maintain contact for next season.",
    },
  ];

  for (const opp of opportunitiesData) {
    await prisma.salesOpportunity.upsert({
      where: { id: opp.id },
      update: {
        title: opp.title,
        stage: opp.stage,
        inquiryValue: opp.inquiryValue,
        quantity: opp.quantity,
        terms: opp.terms,
        notes: opp.notes,
        closedAt: opp.closedAt || null,
        lostReason: opp.lostReason || null,
      },
      create: opp,
    });
  }

  console.log("💼 Seeded 10 Sales Opportunities across all 8 pipeline stages.");

  // ─── 7. Quotations (4 realistic proforma export quotations) ────────────────
  const oppKlang = await prisma.salesOpportunity.findUnique({ where: { id: "seed-opp-006" } });
  const oppAmsterdam = await prisma.salesOpportunity.findUnique({ where: { id: "seed-opp-008" } });
  const oppMaison = await prisma.salesOpportunity.findUnique({ where: { id: "seed-opp-007" } });
  const oppKyoto = await prisma.salesOpportunity.findUnique({ where: { id: "seed-opp-009" } });

  const quotationsData = [
    {
      id: "seed-quot-001",
      quotationNumber: "EXP-2026-000001",
      opportunityId: oppKlang?.id || null,
      leadId: leadKlang!.id,
      status: QuotationStatus.SENT,
      currency: "USD",
      subtotal: 4400.00,
      shippingCost: 400.00,
      total: 4800.00,
      tradeTerm: TradeTerm.CIF,
      validUntil: new Date(Date.now() + 86400000 * 30),
      notes: "CIF Munich proforma with German acoustic frequency verification certificates.",
      createdById: admin.id,
    },
    {
      id: "seed-quot-002",
      quotationNumber: "EXP-2026-000002",
      opportunityId: oppAmsterdam?.id || null,
      leadId: leadAmsterdam!.id,
      status: QuotationStatus.ACCEPTED,
      currency: "USD",
      subtotal: 12500.00,
      shippingCost: 0.00,
      total: 12500.00,
      tradeTerm: TradeTerm.FOB,
      validUntil: new Date(Date.now() + 86400000 * 15),
      notes: "FOB Kolkata port terms. 40x 7-Chakra complete sets with silk ring cushions.",
      createdById: admin.id,
    },
    {
      id: "seed-quot-003",
      quotationNumber: "EXP-2026-000003",
      opportunityId: oppMaison?.id || null,
      leadId: leadMaison!.id,
      status: QuotationStatus.DRAFT,
      currency: "USD",
      subtotal: 6200.00,
      shippingCost: 0.00,
      total: 6200.00,
      tradeTerm: TradeTerm.EXW,
      validUntil: new Date(Date.now() + 86400000 * 20),
      notes: "EXW factory terms. 25 hand-hammered Master bowls Grade AAA with brocade bags.",
      createdById: manager.id,
    },
    {
      id: "seed-quot-004",
      quotationNumber: "EXP-2026-000004",
      opportunityId: oppKyoto?.id || null,
      leadId: leadKyoto!.id,
      status: QuotationStatus.ACCEPTED,
      currency: "USD",
      subtotal: 26500.00,
      shippingCost: 1500.00,
      total: 28000.00,
      tradeTerm: TradeTerm.CIF,
      validUntil: new Date(Date.now() + 86400000 * 45),
      notes: "CIF Osaka Port proforma order. Traditional 7-metal virgin bronze certificates.",
      createdById: admin.id,
    },
  ];

  for (const q of quotationsData) {
    await prisma.quotation.upsert({
      where: { quotationNumber: q.quotationNumber },
      update: {
        status: q.status,
        subtotal: q.subtotal,
        shippingCost: q.shippingCost,
        total: q.total,
        notes: q.notes,
      },
      create: q,
    });
  }

  console.log("📑 Seeded 4 Proforma Quotations (SENT, ACCEPTED, DRAFT).");

  // ─── 8. Email Logs (~18 realistic logs across previous 14 days) ──────────
  const emailLogsData = [
    {
      idempotencyKey: "seed-elog-001",
      recipientEmail: "einkauf@klangtherapie-muenchen.de",
      senderEmail: "sales@exportai.com",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls",
      status: "SENT",
      leadId: leadKlang!.id,
      campaignId: "seed-camp-001",
      sentAt: new Date(Date.now() - 86400000 * 5),
    },
    {
      idempotencyKey: "seed-elog-002",
      recipientEmail: "einkauf@klangtherapie-muenchen.de",
      senderEmail: "sales@exportai.com",
      subject: "RE: Direct Manufacturer Supply — Proforma Quotation EXP-2026-000001",
      status: "REPLIED",
      leadId: leadKlang!.id,
      campaignId: "seed-camp-001",
      sentAt: new Date(Date.now() - 86400000 * 3),
    },
    {
      idempotencyKey: "seed-elog-003",
      recipientEmail: "order@bavaria-wellness-grosshandel.de",
      senderEmail: "sales@exportai.com",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls",
      status: "SENT",
      leadId: (await prisma.buyerLead.findUnique({ where: { normalizedEmail: "order@bavaria-wellness-grosshandel.de" } }))?.id,
      campaignId: "seed-camp-001",
      sentAt: new Date(Date.now() - 86400000 * 4),
    },
    {
      idempotencyKey: "seed-elog-004",
      recipientEmail: "jmiller@zenithsoundwellness.com",
      senderEmail: "sales@exportai.com",
      subject: "Wholesale Hand-Hammered Himalayan Singing Bowls for US Sound Studios",
      status: "SENT",
      leadId: leadZenith!.id,
      campaignId: "seed-camp-002",
      sentAt: new Date(Date.now() - 86400000 * 12),
    },
    {
      idempotencyKey: "seed-elog-005",
      recipientEmail: "jmiller@zenithsoundwellness.com",
      senderEmail: "sales@exportai.com",
      subject: "RE: Wholesale Hand-Hammered Himalayan Singing Bowls — Bulk Pricing",
      status: "REPLIED",
      leadId: leadZenith!.id,
      campaignId: "seed-camp-002",
      sentAt: new Date(Date.now() - 86400000 * 10),
    },
    {
      idempotencyKey: "seed-elog-006",
      recipientEmail: "schen@pacificacousticarts.com",
      senderEmail: "sales@exportai.com",
      subject: "Wholesale Hand-Hammered Himalayan Singing Bowls for US Sound Studios",
      status: "SENT",
      leadId: leadPacific!.id,
      campaignId: "seed-camp-002",
      sentAt: new Date(Date.now() - 86400000 * 9),
    },
    {
      idempotencyKey: "seed-elog-007",
      recipientEmail: "schen@pacificacousticarts.com",
      senderEmail: "sales@exportai.com",
      subject: "RE: Wholesale Hand-Hammered Himalayan Singing Bowls — Contract Terms",
      status: "REPLIED",
      leadId: leadPacific!.id,
      campaignId: "seed-camp-002",
      sentAt: new Date(Date.now() - 86400000 * 7),
    },
    {
      idempotencyKey: "seed-elog-008",
      recipientEmail: "michael@sedonasoundtemple.com",
      senderEmail: "sales@exportai.com",
      subject: "Wholesale Hand-Hammered Himalayan Singing Bowls for US Sound Studios",
      status: "SENT",
      leadId: (await prisma.buyerLead.findUnique({ where: { normalizedEmail: "michael@sedonasoundtemple.com" } }))?.id,
      campaignId: "seed-camp-002",
      sentAt: new Date(Date.now() - 86400000 * 8),
    },
    {
      idempotencyKey: "seed-elog-009",
      recipientEmail: "eleanor@bodhitreeholistic.co.uk",
      senderEmail: "sales@exportai.com",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls",
      status: "SENT",
      leadId: leadBodhi!.id,
      sentAt: new Date(Date.now() - 86400000 * 6),
    },
    {
      idempotencyKey: "seed-elog-010",
      recipientEmail: "eleanor@bodhitreeholistic.co.uk",
      senderEmail: "sales@exportai.com",
      subject: "RE: Certified Handcrafted Singing Bowls — London Stores Sample",
      status: "REPLIED",
      leadId: leadBodhi!.id,
      sentAt: new Date(Date.now() - 86400000 * 4),
    },
    {
      idempotencyKey: "seed-elog-011",
      recipientEmail: "arthur@cotswoldssoundsanctuary.co.uk",
      senderEmail: "sales@exportai.com",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls",
      status: "SENT",
      leadId: (await prisma.buyerLead.findUnique({ where: { normalizedEmail: "arthur@cotswoldssoundsanctuary.co.uk" } }))?.id,
      sentAt: new Date(Date.now() - 86400000 * 6),
    },
    {
      idempotencyKey: "seed-elog-012",
      recipientEmail: "david@pranameditation.ca",
      senderEmail: "sales@exportai.com",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls",
      status: "SENT",
      leadId: (await prisma.buyerLead.findUnique({ where: { normalizedEmail: "david@pranameditation.ca" } }))?.id,
      sentAt: new Date(Date.now() - 86400000 * 5),
    },
    {
      idempotencyKey: "seed-elog-013",
      recipientEmail: "kylie@byronholisticdistribution.com.au",
      senderEmail: "sales@exportai.com",
      subject: "Wholesale 7-Chakra Tuned Bowl Sets for Sound Practitioners",
      status: "SENT",
      leadId: leadByron!.id,
      sentAt: new Date(Date.now() - 86400000 * 4),
    },
    {
      idempotencyKey: "seed-elog-014",
      recipientEmail: "kylie@byronholisticdistribution.com.au",
      senderEmail: "sales@exportai.com",
      subject: "RE: Wholesale 7-Chakra Tuned Bowl Sets — Byron Bay Spa Order",
      status: "REPLIED",
      leadId: leadByron!.id,
      sentAt: new Date(Date.now() - 86400000 * 2),
    },
    {
      idempotencyKey: "seed-elog-015",
      recipientEmail: "cdubois@maisonduson-paris.fr",
      senderEmail: "sales@exportai.com",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls",
      status: "SENT",
      leadId: leadMaison!.id,
      sentAt: new Date(Date.now() - 86400000 * 5),
    },
    {
      idempotencyKey: "seed-elog-016",
      recipientEmail: "cdubois@maisonduson-paris.fr",
      senderEmail: "sales@exportai.com",
      subject: "RE: Direct Manufacturer Supply — Proforma EXP-2026-000003",
      status: "REPLIED",
      leadId: leadMaison!.id,
      sentAt: new Date(Date.now() - 86400000 * 3),
    },
    {
      idempotencyKey: "seed-elog-017",
      recipientEmail: "diederik@amsterdamsoundbath.nl",
      senderEmail: "sales@exportai.com",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls",
      status: "SENT",
      leadId: leadAmsterdam!.id,
      sentAt: new Date(Date.now() - 86400000 * 7),
    },
    {
      idempotencyKey: "seed-elog-018",
      recipientEmail: "invalid-undeliverable@bogus-mail-host.com",
      senderEmail: "sales@exportai.com",
      subject: "Direct Manufacturer Supply: Certified Handcrafted Singing Bowls",
      status: "BOUNCED",
      error: "550 5.1.1 User unknown / Host not found",
      sentAt: new Date(Date.now() - 86400000 * 11),
    },
  ];

  for (const log of emailLogsData) {
    await prisma.emailLog.upsert({
      where: { idempotencyKey: log.idempotencyKey },
      update: {
        status: log.status,
        sentAt: log.sentAt,
      },
      create: log,
    });
  }

  console.log(`✉️ Seeded ${emailLogsData.length} realistic email logs across previous 14 days.`);

  // ─── 9. CRM Activities ───────────────────────────────────────────────────
  const activitiesData = [
    {
      id: "seed-act-001",
      type: ActivityType.DISCOVERY_RUN,
      title: "German Sound Academy Directory Scraped",
      description: "Automated discovery crawler ingested 3 verified wholesale prospects in Germany.",
      userId: admin.id,
      createdAt: new Date(Date.now() - 86400000 * 5),
    },
    {
      id: "seed-act-002",
      type: ActivityType.NOTE,
      title: "Lead Scored & Classified by Gemini",
      description: "Klangtherapie Zentrum München assigned Lead Score 92/100 (High Purchase Intent).",
      userId: admin.id,
      leadId: leadKlang!.id,
      createdAt: new Date(Date.now() - 86400000 * 5),
    },
    {
      id: "seed-act-003",
      type: ActivityType.EMAIL,
      title: "Campaign Email Dispatched",
      description: "Direct manufacturer wholesale introduction sent to Dr. Markus Weber.",
      userId: agent.id,
      leadId: leadKlang!.id,
      createdAt: new Date(Date.now() - 86400000 * 5),
    },
    {
      id: "seed-act-004",
      type: ActivityType.STATUS_CHANGE,
      title: "Buyer Response Received",
      description: "Klangtherapie München replied requesting CIF Munich proforma quotation.",
      userId: agent.id,
      leadId: leadKlang!.id,
      createdAt: new Date(Date.now() - 86400000 * 3),
    },
    {
      id: "seed-act-005",
      type: ActivityType.QUOTATION_SENT,
      title: "Proforma Quotation Generated",
      description: "Commercial Proforma Quotation EXP-2026-000001 ($4,800 CIF Munich) dispatched.",
      userId: admin.id,
      leadId: leadKlang!.id,
      opportunityId: oppKlang?.id || null,
      createdAt: new Date(Date.now() - 86400000 * 2),
    },
    {
      id: "seed-act-006",
      type: ActivityType.OPPORTUNITY_STAGE_CHANGE,
      title: "Opportunity Moved to Negotiation",
      description: "Pacific Acoustic Arts deal advanced to contract negotiation stage ($24,000).",
      userId: agent.id,
      leadId: leadPacific!.id,
      opportunityId: (await prisma.salesOpportunity.findUnique({ where: { id: "seed-opp-005" } }))?.id || null,
      createdAt: new Date(Date.now() - 86400000 * 3),
    },
  ];

  for (const act of activitiesData) {
    await prisma.activity.upsert({
      where: { id: act.id },
      update: {
        type: act.type,
        title: act.title,
        description: act.description,
      },
      create: act,
    });
  }

  console.log("📝 Seeded realistic CRM activities.");
  console.log("✅ EXPORT AI Database seeding finished successfully.");
}

main()
  .catch((e) => {
    console.error("❌ Seeding error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
